version: '3.8'

services:
  super-skylab-app:
    container_name: super-skylab-app
    build: .
    ports:
      - "9010:9010"
    depends_on:
      - super-skylab-db
    networks:
        - nginx-network

  super-skylab-db:
    container_name: super-skylab-db
    image: postgres:17
    environment:
      POSTGRES_DB: superSkyLabDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nginx-network

networks:
    nginx-network:
      external: true

volumes:
  postgres_data: